# jobs:
#   hello_world_job:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#     - name: Hello world action step
#       id: hello
#       uses: thitch97/nodejs/actions/test-action@master
#       with:
#         who-to-greet: 'Mona the Octocat'
#     # Use the output from the `hello` step
#     - name: Get the output time
#       run: echo "The time was ${{ steps.hello.outputs.time }}"

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    name: Update Language Family
    steps:
    - name: Send Dispatch Event
      uses: thitch97/nodejs/actions/dispatch@master
      with:
        event_path: "${{ github.event_path }}"
