name: Renovate

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Renovate updates dependencies'
        required: false
jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v41.0.22
      with:
        token: ${{ secrets.RENOVATE_TOKEN }}